<?php
$reportTitle = 'Rapport PDF - Utilisateurs';
$searchLabel = trim((string) ($searchTerm ?? ''));
$searchLabelDisplay = $searchLabel !== '' ? $searchLabel : 'Tous les utilisateurs';
$generatedAtLabel = isset($generatedAt) && $generatedAt instanceof DateTimeInterface
    ? $generatedAt->format('d/m/Y H:i')
    : date('d/m/Y H:i');
?>

<style>
/* Print stylesheet: hide page chrome but allow the report to flow across pages */
@media print {
    /* hide known chrome elements generated by the layout */
    header, nav, .navbar, .footer, .theme-toggle-floating-wrap, .theme-toggle, .navbar-footer, .brand-fallback { display: none !important; }
    /* any element explicitly marked no-print */
    .no-print { display: none !important; }

    /* ensure report container uses full width and flows naturally */
    .report-page-shell { position: static !important; width: 100% !important; margin: 0 !important; }

    /* table printing helpers: allow rows to break across pages and keep header on each page */
    table.report-table { border-collapse: collapse; width: 100%; }
    thead { display: table-header-group; }
    tfoot { display: table-footer-group; }
    tr { page-break-inside: avoid; }

    /* print page margins */
    @page { size: A4; margin: 10mm; }
}
</style>

<div class="report-page-shell">
    <section class="report-header-card">
        <div>
            <p class="report-eyebrow">Smart Nutrition</p>
            <h1><?= htmlspecialchars($reportTitle) ?></h1>
            <p class="report-subtitle">Export PDF avance du registre des utilisateurs admin.</p>
        </div>

        <div class="report-actions no-print">
            <button type="button" class="btn-admin-secondary" onclick="window.print();">
                <i class="fa-solid fa-print"></i> Imprimer / Sauver en PDF
            </button>
            <a href="/smart_nutrition/index.php?action=users-list" class="btn-admin">
                <i class="fa-solid fa-arrow-left"></i> Retour
            </a>
        </div>
    </section>

    <section class="report-meta-grid">
        <article class="report-meta-card">
            <span>Recherche appliquee</span>
            <strong><?= htmlspecialchars($searchLabelDisplay) ?></strong>
        </article>
        <article class="report-meta-card">
            <span>Utilisateurs affiches</span>
            <strong><?= (int) ($summary['total'] ?? 0) ?></strong>
        </article>
        <article class="report-meta-card">
            <span>Avec empreinte faciale</span>
            <strong><?= (int) ($summary['with_face'] ?? 0) ?></strong>
        </article>
        <article class="report-meta-card">
            <span>Genere le</span>
            <strong><?= htmlspecialchars($generatedAtLabel) ?></strong>
        </article>
    </section>

    <section class="report-table-card">
        <div class="report-table-head">
            <h2>Liste detaillee</h2>
            <p><?= count($users ?? []) ?> ligne(s) dans ce rapport.</p>
        </div>

        <div class="report-table-wrap">
            <table class="report-table">
                <thead>
                    <tr>
                        <th>Nom complet</th>
                        <th>Date naissance</th>
                        <th>Sexe</th>
                        <th>Age</th>
                        <th>Poids</th>
                        <th>Taille</th>
                        <th>Objectif</th>
                        <th>E-mail</th>
                        <th>Role</th>
                        <th>Empreinte faciale</th>
                        <th>Mise a jour</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!empty($users)): ?>
                        <?php foreach ($users as $user): ?>
                            <tr>
                                <td><?= htmlspecialchars(trim((string) ($user['prenom'] ?? '') . ' ' . (string) ($user['nom'] ?? ''))) ?></td>
                                <td><?= htmlspecialchars((string) ($user['date_naissance'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['sexe'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['age'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['poids'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['taille'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['objectif'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['email'] ?? '')) ?></td>
                                <td><?= htmlspecialchars((string) ($user['role'] ?? 'user')) ?></td>
                                <td><?= trim((string) ($user['face_descriptor'] ?? '')) !== '' ? 'Oui' : 'Non' ?></td>
                                <td><?= htmlspecialchars((string) ($user['face_updated_at'] ?? '')) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="11" class="text-center">Aucun utilisateur ne correspond a la recherche.</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </section>
</div>

<script>
window.addEventListener('load', function () {
    setTimeout(function () {
        window.print();
    }, 450);
});
</script>
