

<style>
/* Print stylesheet: hide page chrome but allow the report to flow across pages */
@media print {
    /* hide known chrome elements generated by the layout */
    header, nav, .navbar, .footer, .theme-toggle-floating-wrap, .theme-toggle, .navbar-footer, .brand-fallback { display: none !important; }
    /* any element explicitly marked no-print */
    .no-print { display: none !important; }

    /* ensure report container uses full width and flows naturally */
    .report-page-shell { position: static !important; width: 100% !important; margin: 0 !important; }

    /* table printing helpers: allow rows to break across pages and keep header on each page */
    table.report-table { border-collapse: collapse; width: 100%; }
    thead { display: table-header-group; }
    tfoot { display: table-footer-group; }
    tr { page-break-inside: avoid; }

    /* print page margins */
    @page { size: A4; margin: 10mm; }
}
</style>

<div class="report-page-shell">
    <section class="report-header-card">
        <div>
            <p class="report-eyebrow">Smart Nutrition</p>
            <h1></h1>
            <p class="report-subtitle">Export PDF avance du registre des utilisateurs admin.</p>
        </div>

        <div class="report-actions no-print">
            <button type="button" class="btn-admin-secondary" onclick="window.print();">
                <i class="fa-solid fa-print"></i> Imprimer / Sauver en PDF
            </button>
            <a href="/smart_nutrition/#?action=users-list" class="btn-admin">
                <i class="fa-solid fa-arrow-left"></i> Retour
            </a>
        </div>
    </section>

    <section class="report-meta-grid">
        <article class="report-meta-card">
            <span>Recherche appliquee</span>
            <strong></strong>
        </article>
        <article class="report-meta-card">
            <span>Utilisateurs affiches</span>
            <strong></strong>
        </article>
        <article class="report-meta-card">
            <span>Avec empreinte faciale</span>
            <strong></strong>
        </article>
        <article class="report-meta-card">
            <span>Genere le</span>
            <strong></strong>
        </article>
    </section>

    <section class="report-table-card">
        <div class="report-table-head">
            <h2>Liste detaillee</h2>
            <p> ligne(s) dans ce rapport.</p>
        </div>

        <div class="report-table-wrap">
            <table class="report-table">
                <thead>
                    <tr>
                        <th>Nom complet</th>
                        <th>Date naissance</th>
                        <th>Sexe</th>
                        <th>Age</th>
                        <th>Poids</th>
                        <th>Taille</th>
                        <th>Objectif</th>
                        <th>E-mail</th>
                        <th>Role</th>
                        <th>Empreinte faciale</th>
                        <th>Mise a jour</th>
                    </tr>
                </thead>
                <tbody>
                    
                        
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        
                    
                        <tr>
                            <td colspan="11" class="text-center">Aucun utilisateur ne correspond a la recherche.</td>
                        </tr>
                    
                </tbody>
            </table>
        </div>
    </section>
</div>

<script>
window.addEventListener('load', function () {
    setTimeout(function () {
        window.print();
    }, 450);
});
</script>


