<aside class="sidebar font-sidebar" style="background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(12px); border-right: 1px solid rgba(255, 255, 255, 0.1); border-radius: 12px; padding: 2rem 1rem; min-height: 80vh;">
    <h3 style="color: #38bdf8; margin-bottom: 2rem; text-align: center; font-size: 1.3rem;"><i class="fa-solid fa-layer-group"></i> Modules</h3>
    <ul style="list-style: none; padding: 0; display: flex; flex-direction: column; gap: 0.8rem;">
        <li><a href="index.php?action=activites" style="text-decoration: none; color: #f8fafc; font-weight: 600; padding: 10px; display: block; border-radius: 8px; transition: 0.3s;" onmouseover="this.style.background='#38bdf8'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f8fafc';"><i class="fa-solid fa-dumbbell"></i> Gestion Activité Sportif</a></li>
        <li><a href="#" style="text-decoration: none; color: #f8fafc; font-weight: 600; padding: 10px; display: block; border-radius: 8px; transition: 0.3s;" onmouseover="this.style.background='#38bdf8'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f8fafc';"><i class="fa-solid fa-utensils"></i> Gestion Recettes</a></li>
        <li><a href="#" style="text-decoration: none; color: #f8fafc; font-weight: 600; padding: 10px; display: block; border-radius: 8px; transition: 0.3s;" onmouseover="this.style.background='#38bdf8'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f8fafc';"><i class="fa-solid fa-cart-shopping"></i> Gestion eCommerce</a></li>
        <li><a href="#" style="text-decoration: none; color: #f8fafc; font-weight: 600; padding: 10px; display: block; border-radius: 8px; transition: 0.3s;" onmouseover="this.style.background='#38bdf8'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f8fafc';"><i class="fa-solid fa-users"></i> Gestion Communauté</a></li>
        <li><a href="#" style="text-decoration: none; color: #f8fafc; font-weight: 600; padding: 10px; display: block; border-radius: 8px; transition: 0.3s;" onmouseover="this.style.background='#38bdf8'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f8fafc';"><i class="fa-solid fa-calendar"></i> Gestion Planning</a></li>
        <li><a href="#" style="text-decoration: none; color: #f8fafc; font-weight: 600; padding: 10px; display: block; border-radius: 8px; transition: 0.3s;" onmouseover="this.style.background='#38bdf8'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f8fafc';"><i class="fa-solid fa-user-gear"></i> Gestion Utilisateurs</a></li>
        <li style="margin-top: 2rem;"><a href="index.php?action=admin_login" style="text-decoration: none; color: #f43f5e; font-weight: 600; padding: 10px; display: block; border-radius: 8px; border: 1px solid #f43f5e; text-align: center; transition: 0.3s;" onmouseover="this.style.background='#f43f5e'; this.style.color='#fff';" onmouseout="this.style.background='transparent'; this.style.color='#f43f5e';"><i class="fa-solid fa-shield-halved"></i> BackOffice Admin</a></li>
    </ul>
</aside>
